### PR TITLE
Support contamination distribution parameters as mapping

### PR DESCRIPTION
**Pull request by wenzeslaus**
The two parameters for the Beta distribution for contaminants can now be specified by keys a and b instead of a list of parameters. This makes the syntax in tabular configuration formats easier (only keys, not indices or two values instead of one JSON list as value).

### CODE REVIEW

**Comment by wenzeslaus** [comment]
@kellynm Mostly for you to be aware of this. Should avoid `[1, 2]` in the spreadsheet config in this case. See the doc: https://github.com/ncsu-landscape-dynamics/popsborder/pull/175/files?short_path=c941c55#diff-c941c5542a018a3c0c04e723b5f741dfdd8e388d180dd5da9d66c466f54e09a1

**Review by kellynm — COMMENTED** [review]
Great! Do you want to change this in the user friendly config saved in the test folder for this PR? I could update the spreadsheet formatting and add to this PR if you like.

**Comment by wenzeslaus** [comment]
Good point, but I think there is no need to change the test data. On the other hand, we do need that proper example we talked about. If you prepare a spreadsheet for that in a separate PR that would be perhaps the best thing to do.

**Comment by kellynm** [comment]
Ok sounds good. I'll create a PR for the branch with the example I've been working on and include these changes in the config spreadsheet there.

**Pull request merged**
